SIRENE
=====================================================

Row {data-height=500}
-------------------------------------

### Identification

```{r}
sirenUL <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "siren",
							 .default = NA)

nicUL <-
	mydt |> 
	insee_utils_get_nic()

linkAvisSit <- 
	paste0(identsiren, nicUL) |> 
	insee_utils_avis_sit(url = TRUE) |> 
	apimisc_make_link(text = "Avis de situation au répertoire")

categEntr <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "categorieEntreprise",
							 .default = NA)

denomUL <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "periodesUniteLegale",
							 .default = NA) |> 
	data.frame() |> 
	dplyr::slice(1) |> 
	dplyr::select(denominationUniteLegale) |> 
	dplyr::pull()

dateCrea <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "dateCreationUniteLegale",
							 .default = NA) |> 
	as.Date(format = "%Y-%m-%d")

trEffectif <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "trancheEffectifsUniteLegale",
							 .default = NA)

libEffectif <- 
	findmytreff(trEffectif)

actiPpalUL <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "periodesUniteLegale",
							 .default = NA) |> 
	data.frame() |> 
	dplyr::slice(1) |> 
	dplyr::select(activitePrincipaleUniteLegale) |> 
	dplyr::pull()

libActiUL <- 
	nafniv5 |> 
	dplyr::filter(Code == actiPpalUL) |> 
	dplyr::select(Libellé) |> 
	dplyr::pull()

catJuUL <- 
	mydt |> 
	purrr::pluck("unitesLegales",
							 "periodesUniteLegale",
							 .default = NA) |> 
	data.frame() |> 
	dplyr::slice(1) |> 
	dplyr::select(categorieJuridiqueUniteLegale) |> 
	dplyr::pull()

libCatJuUL <- findmycj(catJuUL)

vbs1 <- list(
	bslib::value_box(
		title = "",
		value = denomUL,
		theme = "pink",
		showcase = bsicons::bs_icon("fingerprint"),
		shiny::h5(bsicons::bs_icon("activity"),
							paste0(actiPpalUL, " (", libActiUL, ")")),
		shiny::h6(paste0("SIREN : ", sirenUL)),
		shiny::h6(paste0("Date de création : ", dateCrea)),
		shiny::h6("Tranche d'effectif : ", libEffectif),
		shiny::h6(paste0("Catégorie juridique : ", catJuUL, " (", libCatJuUL, ")")),
		shiny::h6(paste0("Catégorie d'entreprise: ", categEntr)),
		htmltools::HTML(linkAvisSit),
		shiny::p(""))
)

bslib::layout_column_wrap(
  width = "250px",
	height = "350px",
  !!!vbs1
)
```

### Etablissements

```{r}
mydt |> 
	purrr::pluck("unitesLegales",
							 "periodesUniteLegale",
							 .default = NA) |> 
	data.frame() |> 
	dplyr::rename(eaul = etatAdministratifUniteLegale) |> 
	dplyr::rename(apul = activitePrincipaleUniteLegale) |> 
	dplyr::select(-tidyselect::any_of(c(
					"changementNomUsageUniteLegale"))) |> 
	dplyr::select(dateFin, dateDebut, eaul, apul, denominationUniteLegale) |> 
	DT::datatable(rownames = FALSE)
```

